version: '3.8'

services:
  laravel:
    image: laravel/laravel
    container_name: laravel_app
    restart: always
    volumes:
      - ./laravel:/var/www/html
    ports:
      - "8000:80"
    environment:
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - LOG_CHANNEL=stack
      - LOG_DEPRECATIONS_CHANNEL=null
      - LOG_LEVEL=debug
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=
    depends_on:
      - db

  vue:
    image: node:14
    container_name: vue_app
    restart: always
    volumes:
      - ./vue:/app
    working_dir: /app
    ports:
      - "8080:8080"
    command: bash -c 'npm install && npm run serve'

  db:
    image: mysql:5.7
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: 
      MYSQL_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
