version: '3'
services:
  laravel:
    image: laravel/laravel
    container_name: laravel_app
    restart: always
    volumes:
      - ./laravel:/var/www/html
    ports:
      - 8000:80
    environment:
      - APP_KEY=base64:xxxxxxxxxx
      - APP_PORT=8000

  vue:
    image: node:14
    container_name: vue_app
    restart: always
    volumes:
      - ./vue:/app
    working_dir: /app
    ports:
      - 8080:8080
    command: bash -c 'npm install && npm run serve'
